### PR TITLE
Allow building under Kaleidoscope-Hardware-Virtual

### PR DESCRIPTION
**Pull request by cdisselkoen**
LED-Stalker is another one of those plugins that, currently, doesn't build under Kaleidoscope-Hardware-Virtual.  The problem here is messy, and this proposed solution is messier than I'd like; maybe there's a better way.

Hardware-Virtual has a dependency on the C++ `<string>` header, at least how I've written it.  (It builds with standard toolchain, so there's no obvious reason why it can't pull in any C++ standard-library functions it wants, during its own builds.)  The problem is that the `<string>` header pulls in the standard-library definition of `std::min`, and in particular undefines any previous definition of `min`.  This is in conflict with the Arduino core, which `#define`s `min` as a macro.

This proposed solution has LED-Stalker (the only user of `min` anywhere in Kaleidoscope or the Arduino-Boards plugins) use an `ourMin` instead of `min`, where `ourMin` is`#define`d to either `std::min` or the `min` from Arduino core, depending on whether it's a virtual build or not.

Solutions that seem worse and/or don't work include:
* having LED-Stalker use `std::min` for all builds (if that's even possible - it probably isn't)
* just redefine `min` after including `<string>` - doesn't work, because `<string>` relies on access to `std::min`
* for virtual builds, `#define min std::min` - good idea, but doesn't work because `<string>` uses explicit code like `std::min` which gets expanded to `std::std::min` after substitution
* Namespace hijinks - since everything in LED-Stalker takes place in `namespace kaleidoscope`, could we define `kaleidoscope::min` to be our min and let `std::min` be `std::min`?  No - unfortunately the preprocessor is not namespace-aware, so we can't have a `#define` that only takes effect in a certain namespace

More invasive potential solutions include:
* Having Kaleidoscope core supply an `ourMin` (or `kaleidoscope_min` or something) with this same definition, instead of just defining `ourMin` in LED-Stalker.  I thought this seemed like overkill when LED-Stalker is the only user, but on the other hand, this *would* prevent the same problem from popping up in the future when someone else needs `min`
* Rewrite Hardware-Virtual to not depend on `<string>` - I'd rather not if I don't have to.  Also, other C++ headers may also require `std::min`.  It seems reasonable that there should be some way for Arduino's `min` and `std::min` to coexist

### CODE REVIEW

**Comment by obra** [comment]
In general, I'm pretty afraid of things where we break bits of the Arduino standard library. :/

**Comment by cdisselkoen** [comment]
Sure.  Just to clarify, do you not like the fact that the virtual and real-hardware builds use different implementations of `min`?  Or the fact that the virtual build uses a non-Arduino standard function?  Or something else?

**Comment by obra** [comment]
Oops. Sorry, What I was reacting negatively to was having to special case Arduino builtins in plugin code.

I'm thrilled for the Virtual build to use whatever tools it needs, so long as it doesn't bleed over  into requiring special-casing in library code. (The ifdef for the HID implementation isn't _ideal_ to me, but is totally understandable and I'm fine with it until we figure out a cleaner factoring.)

I know that the Arduino way of doing things isn't exactly the cleanest in the world, but it's what we're built on. :/ 

Edit: It was the thing you added in the Edit ;)

**Comment by cdisselkoen** [comment]
All right, I've managed to solve this internally in Hardware-Virtual with `38293be` - and much more cleanly, I might add.

Thanks for pushing me - being forced to think around the above problem led me to a solution much better than originally proposed.

**Comment by obra** [comment]
Nice!

**Comment by algernon** [comment]
Perhaps a wrong idea, but wouldn't using `::min` in the plugin, and `using namespace std` or something similar in the virtual hardware plugin help?

**Comment by algernon** [comment]
(And that's what I get for keeping a tab open, and not refreshing...)

**Comment by cdisselkoen** [comment]
(1) After macro replacement, `::min` would be something like `::((calculations))` - macro replacement ignores namespaces.  Part of the problem is that the arduino `min` isn't a function (in any namespace), but a macro.

(2) Even if it worked, we'd still have the same objection that we're blacklisting LED-Stalker from using a standard arduino library function in the standard way.

**Comment by obra** [comment]
With Arduino's default toolchain, could min be turned into a function and have user code work unchanged? We might want to upstream a patch, if so.

**Comment by cdisselkoen** [comment]
It's kinda moot because I was able to address this issue in Hardware-Virtual.

I could foresee problems with making `min` a function - what type signature would it have?  The advantage of a macro is it implicitly works with any types that support comparison.  The solution I can immediately think of is that `min` should be a templated function (I think that's how `std::min` does it), but I don't think non-C++ C supports templates, and even though all our code is Arduino C++, I imagine the upstream Arduino wants to remain C-compatible?  I could be wrong about any of these points.

Regardless, I don't think we need to worry about this - I'm pretty sure my solution in Hardware-Virtual, and solutions like it, should suffice in any future scenarios too.  Basically, we can keep any additional standard-library headers used in virtual builds from even being included when compiling Kaleidoscope and plugin code, and have them only included when compiling the Hardware-Virtual plugin code and its provided version of the Arduino core.  From a practical standpoint, this just means we keep any additional standard-library header includes out of .h files and put them only in .cpp files, refactoring as necessary.  Arguably it's cleaner that way too.

**Pull request closed without merging**
